import Head from 'next/head'
import Mode from './Mode'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import {MdEmail} from 'react-icons/md'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shymala Sidharth Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 '>
        <section className='min-h-screen'>
         
          <nav className='py-10 mb-12 flex justify-between'>
           
            <ul className='flex items-center'>
              <li>
                <Mode className='cursor-pointer text-2xl' />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8'
              href=''>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Shymala Sidharth</h2>
            <h3 className='text-2xl py-2'>Full Stack Software Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Software developer from Auckland, New Zealand. I have a passion for building web applications and I love to learn new technologies.</p>
          </div>
          <div className='text-5xl flex justify-center gap-20 py-3 text-gray-700'>
            <a href='https://github.com/shymala-sidharth' target='_blank' rel="noreferrer">
            <AiFillGithub/>
            </a>
            <a href='https://www.linkedin.com/in/shymala-sidharth-5420a1129/' target='_blank' rel='noreferrer'>
            <AiFillLinkedin/> 
            </a>
            <a>
            <MdEmail/>
            </a>
          </div>

        </section>
      </main>

      </div>
  
  )
}
